Repository boostcampwm2023/and02-PlanJ, pull requests merged in 2023-12, with the labels that each got.

#173 [J033] 일정 상세 조회 기능 구현
  be/Dockerfile
  be/nginx/Dockerfile
  be/nginx/nginx.conf
  be/src/category/category.service.ts
  be/src/category/entity/category.entity.ts
  be/src/friend/entity/friend.entity.ts
  be/src/friend/friend.service.ts
  be/src/guard/auth.guard.ts
  be/src/image/image.service.spec.ts
  be/src/schedule-api/interface/alarmInfo.response.ts
  be/src/schedule-api/interface/location.response.ts
  be/src/schedule-api/interface/participant.response.ts
  be/src/schedule-api/interface/repetition.response.ts
  be/src/schedule-api/interface/schedule-detail.response.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/schedule.response.ts
  be/src/schedule/entity/repetition.entity.ts
  be/src/schedule/entity/schedule-alarm.entity.ts
  be/src/schedule/entity/schedule-location.entity.ts
  be/src/schedule/entity/schedule-metadata.entity.ts
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/repetition.service.ts
  be/src/schedule/schedule-alarm.service.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.service.ts
  be/src/user-api/user-api.controller.ts
  be/src/user/entity/user.entity.ts
  be/src/utils/domain/alarm-type.enum.ts
  be/src/utils/domain/cycle-type.enum.ts
Labels: Be, Must, :field_hockey: Feat, :stethoscope: Refactor

#180 [J033] 실패한 이유를 적는 메모를 추가하는 기능 구현
  be/src/schedule-api/dto/add-retrospective-memo.dto.ts
  be/src/schedule-api/dto/alarmInfo.response.ts
  be/src/schedule-api/dto/location.response.ts
  be/src/schedule-api/dto/participant.response.ts
  be/src/schedule-api/dto/repetition.response.ts
  be/src/schedule-api/dto/schedule-detail.response.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat, :stethoscope: Refactor

#172 [K020] 친구 목록 요청 수정, Alarm 관련 수정
  PlanJ/.gitignore
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AlarmInfoDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AppDatabase.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/AlarmInfo.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/User.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetDetailScheduleResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetFriendResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/LoginResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/LoginApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/MainApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/AlarmRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanJReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanjAlarm.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/RestartAlarmReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleShowMapFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/dialog_friend_info.xml
  PlanJ/app/src/main/res/layout/item_friend.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix

#191 [J033] change method to Patch
  be/src/user-api/user-api.controller.ts
Labels: Be, Must, :lady_beetle: Fix

#192 [K026, K041] 일정 라디오, 삭제 api 연결, 카테고리 상세 일정 api, 설정 프로필 화면 삭제 및 로그인 버그 수정, 모듈 분리
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/LogInModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainRepositoryModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/NaverDirectionModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/SearchMapModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Category.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetScheduleCheckedResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/MainApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/RestartAlarmReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleDoneListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryClickListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryListAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
  PlanJ/app/src/main/res/drawable/ic_cancel.xml
  PlanJ/app/src/main/res/layout/fragment_category_detail.xml
  PlanJ/app/src/main/res/layout/fragment_setting.xml
  PlanJ/app/src/main/res/navigation/login_nav.xml
  PlanJ/app/src/main/res/navigation/main_nav.xml
Labels: And, :lady_beetle: Fix, :stethoscope: Refactor

#193 [K020] 일정 상세/편집 화면 api 요청, 일정 편집관련 다이얼로그 수정
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Location.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Participant.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetDetailScheduleResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetSchedulesResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PatchScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PatchScheduleResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleClickListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/AddFriendDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantProfileAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantProfileAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/layout/item_participant_profile.xml
  PlanJ/app/src/main/res/navigation/main_nav.xml
  PlanJ/app/src/main/res/navigation/schedule_nav.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor

#195 [J033] 미분류 카테고리 조회 오류 수정
  be/src/category/category.service.ts
Labels: Be, Must, :lady_beetle: Fix

#196 [J033] 일정 완료 체크 응답에 속성 추가
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/check-schedule.response.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat

#199 [J033] 도커 파일 수정
  be/.dockerignore
  be/Dockerfile
Labels: Be, Should, :field_hockey: Feat, :stethoscope: Refactor

#201 [J033] 회고 메모 조회 기능 추가
  be/.dockerignore
  be/src/config/typeorm.config.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/memo.response.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
Labels: Be, Must, :field_hockey: Feat

#200 [K026] 홈 화면 토글 버튼 버그 수정, 실패 작성글 기능 구현, 홈 화면 새로고침 기능 구현
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/ScheduleSegment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetScheduleCheckedResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PostScheduleAddMemoBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/MainApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/SegmentScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/SegmentScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFailDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/res/layout/dialog_fail_write.xml
  PlanJ/app/src/main/res/layout/fragment_category_detail.xml
  PlanJ/app/src/main/res/layout/fragment_home.xml
  PlanJ/app/src/main/res/layout/fragment_setting_fail.xml
  PlanJ/app/src/main/res/layout/item_fail_memo.xml
  PlanJ/app/src/main/res/layout/item_list_schedule.xml
  PlanJ/app/src/main/res/navigation/main_nav.xml
  PlanJ/app/src/main/res/xml/item_today_schedule_scene.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix

#197 [K020] 일정 수정 시 참가자 추가 구현
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Participant.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PatchScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantsFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantsListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantsViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleStartMapFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/dialog_friend_info.xml
  PlanJ/app/src/main/res/layout/dialog_participants.xml
  PlanJ/app/src/main/res/layout/fragment_schedule_participants.xml
  PlanJ/app/src/main/res/layout/item_participant.xml
  PlanJ/app/src/main/res/layout/item_participant_profile.xml
  PlanJ/app/src/main/res/navigation/main_nav.xml
  PlanJ/app/src/main/res/navigation/schedule_nav.xml
  PlanJ/gradle/libs.versions.toml
Labels: And, :field_hockey: Feat

#205 [J033] 업데이트 관련 수정
  be/src/schedule-api/dto/alarmInfo.response.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/schedule-alarm.dto.ts
  be/src/schedule/dto/schedule-location.dto.ts
  be/src/schedule/entity/schedule-alarm.entity.ts
  be/src/schedule/participate.repository.ts
  be/src/schedule/participate.service.ts
  be/src/schedule/schedule-alarm.service.ts
  be/src/schedule/schedule-location.service.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.service.ts
  be/src/user-api/user-api.controller.ts
Labels: Be, Must, :field_hockey: Feat

#206 [J033] swagger 적용
  be/nest-cli.json
  be/package-lock.json
  be/package.json
  be/src/category-api/category-api.controller.ts
  be/src/category/dto/add-category.dto.ts
  be/src/category/dto/delete-category.dto.ts
  be/src/category/dto/update-category.dto.ts
  be/src/friend/friend.controller.ts
  be/src/main.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/dto/delete-schedule.dto.ts
  be/src/schedule/dto/repetition.dto.ts
  be/src/schedule/dto/update-schedule.dto.ts
  be/src/user-api/user-api.controller.ts
Labels: Be, Should, :field_hockey: Feat, :abacus: Chore

#207 [J033] 친구 삭제 기능 추가, 오류 수정
  be/src/friend/friend.controller.ts
  be/src/friend/friend.service.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix

#208 [J033] 반복 일정 기능 추가
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/participate.service.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat

#209 [J033] dto 오류 수정
  be/src/schedule/dto/schedule-location.dto.ts
Labels: Be, Must, :lady_beetle: Fix

#211 [J033] 메모 수정
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :lady_beetle: Fix

#212 [J033] 공유 일정 삭제 문제 해결
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/participate.service.ts
Labels: Be, Must, :lady_beetle: Fix

#213 [J033] 반복 일정 수정 버그 해결
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :lady_beetle: Fix

#215 [K041] 지난일정 토글버튼 터치 차단, 닉네임 조건적용, 친구 삭제
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/DeleteFriendBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/MainApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpState.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleDialog.kt
  PlanJ/app/src/main/res/layout/fragment_setting.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat

#219 [J033] 알람이 설정된 일정 조회 기능 추가
  be/src/friend/friend.controller.ts
  be/src/schedule-api/dto/alarmInfo.response.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/alarm-schedule.response.ts
  be/src/schedule/dto/schedule-alarm.dto.ts
  be/src/schedule/entity/schedule-alarm.entity.ts
  be/src/schedule/schedule-alarm.service.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
Labels: Be, Must, :field_hockey: Feat

#221 [J033] 푸시 알림 기능 추가
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/config/firebase.config.ts
  be/src/friend/friend.module.ts
  be/src/friend/friend.service.ts
  be/src/push/push.module.ts
  be/src/push/push.service.ts
  be/src/schedule-api/schedule-api.module.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/user-api/user-api.controller.ts
  be/src/user-api/user-api.service.ts
  be/src/user/dto/user-login.dto.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.service.ts
  be/tsconfig.json
Labels: Be, Should, :field_hockey: Feat

#222 [J033] 로그인 오류 수정
  be/src/user-api/user-api.service.ts
  be/src/user/dto/user-login.dto.ts
Labels: Be, Must, :lady_beetle: Fix

#224 [J033] 삭제된 일정이 알람 설정시 조회되는 문제 해결
  be/src/schedule/schedule-meta.repository.ts
Labels: Be, Must, :lady_beetle: Fix

#225 [K026] 버그 수정, 파이어 베이스 FCM 서버와 연동
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/SignInRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanJReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanjFirebaseMessagingService.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanjViewService.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarFragmentStateAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragmentViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleBottomSheetDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFailDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleSearchAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/SearchMapClickListener.kt
  PlanJ/app/src/main/res/layout/fragment_sign_in.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor

#229 [K020] 서버에 저장된 3일간의 알림 정보를 받아와 알람 set, 로컬에 저장
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanjAlarm.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeViewModel.kt
  PlanJ/app/src/main/res/layout/fragment_home.xml
Labels: And, :field_hockey: Feat

#232 [J033] fix schedule attribute
  be/nginx/nginx.conf
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/schedule.response.ts
  be/src/schedule/schedule-meta.service.ts
Labels: Be, Must, :field_hockey: Feat

#233 [J033] fix
  be/Dockerfile
  be/docker-compose.yml
  be/ecosystem-prod.config.js
  be/src/user/user.service.ts
Labels: Be, Must, :lady_beetle: Fix

#234 Feat: add attribute on response
  be/src/schedule-api/dto/participant.response.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat

#235 Fix: fix shared schedule
  be/src/schedule/participate.repository.ts
Labels: Be, Must, :lady_beetle: Fix

#236 [J033] 참가자가 공유 일정 삭제 시 발생하는 문제 해결
  be/Dockerfile
  be/src/push/push.service.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/participate.service.ts
  be/src/schedule/schedule-meta.service.ts
Labels: Be, Must, :lady_beetle: Fix

#237 [K020] notification 앱 설정 화면 이동 및 토스트 메시지 추가
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Participant.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanJReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantsFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantsViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchViewModel.kt
  PlanJ/app/src/main/res/drawable/ic_chevron_right.xml
  PlanJ/app/src/main/res/layout/activity_search.xml
  PlanJ/app/src/main/res/layout/dialog_fail_write.xml
  PlanJ/app/src/main/res/layout/fragment_setting.xml
  PlanJ/app/src/main/res/menu/toolbar_menu.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor

#243 [J033] 오류 수정
  be/src/schedule-api/schedule-api.service.ts
Labels: Be, Must, :lady_beetle: Fix

#242 [K020] 다이얼로그 네비게이션 연결, 프로필 이미지 변경 관련 오류 수정
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/MessageResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/MainApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialogListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialogListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleBottomSheetDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/fragment_setting.xml
  PlanJ/app/src/main/res/menu/toolbar_menu.xml
  PlanJ/app/src/main/res/navigation/schedule_nav.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor

#245 [J033] 작성자 표시 문제 해결
  be/src/schedule-api/schedule-api.service.ts
Labels: Be, Must, :lady_beetle: Fix

#248 [J033] fix push
  be/docker-compose.yml
  be/src/friend/friend.service.ts
  be/src/push/push.service.ts
  be/src/schedule-api/schedule-api.service.ts
Labels: Be, Must, :lady_beetle: Fix

#249 [J033] fix push message
  be/src/push/push.service.ts
Labels: Be, Must, :lady_beetle: Fix

#250 [K020] 로그인/회원가입 스크롤, item_schedule 라디오버튼형태로 변경
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
  PlanJ/app/src/main/res/layout/fragment_setting_fail.xml
  PlanJ/app/src/main/res/layout/fragment_sign_in.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/layout/item_schedule.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix

#252 [J033] 공유 일정 삭제 문제 수정
  be/src/main.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/utils/middleware/disable-connection.global.ts
  be/src/utils/middleware/set-connection-header.middleware.ts
  be/src/utils/middleware/shut-down.ts
Labels: Be, Must, :lady_beetle: Fix

#253 [J033] 공유 일정 삭제 문제 해결
  be/src/schedule-api/schedule-api.service.ts
Labels: Be, Must, :lady_beetle: Fix

#254 Fix: fix shared schedule
  be/src/push/dto/payload.dto.ts
  be/src/push/push.service.ts
Labels: Be, Must, :lady_beetle: Fix

#255 [J033] 알람 부분 버그 수정
  be/src/push/push.service.ts
Labels: Be, Must, :lady_beetle: Fix

#256 [K020] 오류 해결
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/alarm/PlanJReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/alarm/PlanjAlarm.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/alarm/PlanjFirebaseMessagingService.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/alarm/RestartAlarmReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/widget/PlanjRemoteViewsFactory.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/widget/PlanjViewService.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/widget/PlanjWidgetProvider.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/widget/UpdateWidget.kt
  PlanJ/app/src/main/res/drawable/ic_exit.xml
  PlanJ/app/src/main/res/layout/fragment_sign_in.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :lady_beetle: Fix
