Repository boostcampwm2023/and02-PlanJ, pull requests merged in 2023-11, with the labels that each got.

#40 [K020] 로그인 화면 구현 및 네비게이션 추가
  PlanJ/.idea/deploymentTargetDropDown.xml
  PlanJ/.idea/misc.xml
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/LoginActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/res/drawable/ic_delete.xml
  PlanJ/app/src/main/res/drawable/img_logo.xml
  PlanJ/app/src/main/res/drawable/img_naver.xml
  PlanJ/app/src/main/res/drawable/round_main1.xml
  PlanJ/app/src/main/res/drawable/round_white_stroke.xml
  PlanJ/app/src/main/res/layout/activity_login.xml
  PlanJ/app/src/main/res/layout/fragment_sign_in.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/navigation/login_nav.xml
  PlanJ/app/src/main/res/values/colors.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat

#41 [K026] 하단 네비게이션, 뷰페이저, 탭레이아웃, Today UI 구 현
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/ListFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MyFragmentPagerAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/WeekFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
  PlanJ/app/src/main/res/color/bottom_clicked.xml
  PlanJ/app/src/main/res/drawable/ic_add.xml
  PlanJ/app/src/main/res/drawable/ic_home.xml
  PlanJ/app/src/main/res/drawable/ic_list.xml
  PlanJ/app/src/main/res/drawable/ic_notifications.xml
  PlanJ/app/src/main/res/drawable/ic_search.xml
  PlanJ/app/src/main/res/drawable/ic_user.xml
  PlanJ/app/src/main/res/layout/activity_main.xml
  PlanJ/app/src/main/res/layout/activity_schedule.xml
  PlanJ/app/src/main/res/layout/activity_search.xml
  PlanJ/app/src/main/res/layout/fragment_home.xml
  PlanJ/app/src/main/res/layout/fragment_list.xml
  PlanJ/app/src/main/res/layout/fragment_setting.xml
  PlanJ/app/src/main/res/layout/fragment_today.xml
  PlanJ/app/src/main/res/layout/fragment_week.xml
  PlanJ/app/src/main/res/menu/bottom_menu.xml
  PlanJ/app/src/main/res/menu/toolbar_menu.xml
  PlanJ/app/src/main/res/navigation/login_nav.xml
  PlanJ/app/src/main/res/navigation/main_nav.xml
  PlanJ/app/src/main/res/values/colors.xml
Labels: And, :field_hockey: Feat

#45 [J161] 회원가입 및 로그인 기능 구현
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/app.controller.spec.ts
  be/src/app.controller.ts
  be/src/app.module.ts
  be/src/app.service.ts
  be/src/auth/auth.controller.spec.ts
  be/src/auth/auth.controller.ts
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.spec.ts
  be/src/auth/auth.service.ts
  be/src/auth/dto/create-user.dto.ts
  be/src/auth/dto/user-login.dto.ts
  be/src/auth/user.entity.ts
  be/src/auth/user.repository.ts
  be/src/config/typeorm.config.ts
  be/src/main.ts
  be/test/app.e2e-spec.ts
Labels: Be, Must, :page_with_curl: Docs, :field_hockey: Feat, :abacus: Chore

#44 [K020] 회원가입 ui 구현 및 화면 이동 구현
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/res/anim/from_left_to_right.xml
  PlanJ/app/src/main/res/anim/from_right_to_left.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/navigation/login_nav.xml
  PlanJ/app/src/main/res/values/strings.xml
  README.md
Labels: And, :field_hockey: Feat

#47 [K041] 주간 달력 구현
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CalendarAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/WeekFragment.kt
  PlanJ/app/src/main/res/layout/activity_main.xml
  PlanJ/app/src/main/res/layout/fragment_today.xml
  PlanJ/app/src/main/res/layout/fragment_week.xml
  PlanJ/app/src/main/res/layout/item_day.xml
  PlanJ/app/src/main/res/values/strings.xml
  PlanJ/app/src/main/res/values/week_array.xml
Labels: And, :field_hockey: Feat

#49 [J161] 원격 db 서버 생성, db 접속 정보 환경변수로 숨김
  .gitignore
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/config/typeorm.config.ts
Labels: Be, Must, :field_hockey: Feat

#51 [K020] 회원가입 UI 유효성 검증 추가
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpState.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpViewModel.kt
  PlanJ/app/src/main/res/drawable/round_gray.xml
  PlanJ/app/src/main/res/drawable/selector_enable.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat

#52 [K020] 회원가입 네트워크 통신 추가
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SignUpRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/PlanJAPI.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/LoginActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpViewModel.kt
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/gradle/libs.versions.toml
Labels: And, :field_hockey: Feat

#53 [J161] 회원가입 성공 시 응답 메시지 body 형식 변경
  be/src/app.module.ts
  be/src/auth/auth.controller.ts
  be/src/auth/auth.service.ts
  be/src/auth/user.repository.ts
  be/src/schedule/schedule.controller.spec.ts
  be/src/schedule/schedule.controller.ts
  be/src/schedule/schedule.entity.ts
  be/src/schedule/schedule.module.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.spec.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :lady_beetle: Fix

#55 [J033] 응답 데이터 통일을 위한 Interface 추가
  be/src/auth/auth.controller.ts
  be/src/auth/auth.service.ts
  be/src/auth/user.repository.ts
  be/src/main.ts
  be/src/utils/http.response.ts
Labels: Be, Must, :field_hockey: Feat

#57 [J033] 회원 정보 수정 구현
  be/src/auth/auth.controller.ts
  be/src/auth/auth.service.ts
  be/src/auth/dto/user-modify.dto.ts
  be/src/auth/user.repository.ts
  be/src/utils/http.response.ts
Labels: Be, Must, :field_hockey: Feat

#58 [K020] 로그인 요청 및 Response Status Code에 따른 처리
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/LoginResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SignInRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/ApiResult.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/PlanJAPI.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpState.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpViewModel.kt
  PlanJ/app/src/main/res/layout/fragment_sign_in.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/values/strings.xml
  PlanJ/gradle/libs.versions.toml
Labels: And, :field_hockey: Feat

#59 [K026] today 화면 일정 추가, 토글로 일정 보기/숨기기 기능
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Repetition.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SignUpResult.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/PlanJAPI.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/DummySchedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/ScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/ScheduleViewHolder.kt
  PlanJ/app/src/main/res/drawable/checkbox.xml
  PlanJ/app/src/main/res/drawable/checkbox_check.xml
  PlanJ/app/src/main/res/drawable/checkbox_uncheck.xml
  PlanJ/app/src/main/res/drawable/ic_arrow_right.xml
  PlanJ/app/src/main/res/drawable/ic_circle.xml
  PlanJ/app/src/main/res/drawable/ic_outline_circle.xml
  PlanJ/app/src/main/res/layout/fragment_today.xml
  PlanJ/app/src/main/res/layout/item_schedule.xml
Labels: And, :field_hockey: Feat

#61 [K026] today 화면을 2개의 어댑터로 UI 구현, 모션 레이아웃을 이용해 일정 보이기/숨기기 기능 구현
  PlanJ/.idea/deploymentTargetDropDown.xml
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/res/layout/fragment_today.xml
  PlanJ/app/src/main/res/layout/item_schedule.xml
  PlanJ/app/src/main/res/layout/item_today_schedule.xml
  PlanJ/app/src/main/res/values/strings.xml
  PlanJ/app/src/main/res/xml/item_today_schedule_scene.xml
Labels: And, :field_hockey: Feat

#62 [J033] cross-env 모듈을 이용하여 동적으로 환경 변수 설정
  be/nest-cli.json
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/auth/dto/user-modify.dto.ts
  be/src/auth/user.repository.ts
  be/src/config/dbConfig.ts
  be/src/config/typeorm.config.ts
  be/src/main.ts
  be/src/schedule/schedule.controller.spec.ts
  be/src/schedule/schedule.controller.ts
  be/src/schedule/schedule.service.spec.ts
  be/src/schedule/schedule.service.ts
  be/src/utils/http.response.ts
  be/tsconfig.json
Labels: Be, :field_hockey: Feat, :abacus: Chore, :stethoscope: Refactor

#63 [K020] 일정 추가 UI
  PlanJ/.idea/misc.xml
  PlanJ/app/src/main/res/drawable/ic_arrow_back.xml
  PlanJ/app/src/main/res/drawable/ic_check.xml
  PlanJ/app/src/main/res/drawable/ic_location.xml
  PlanJ/app/src/main/res/drawable/round_light_gray.xml
  PlanJ/app/src/main/res/layout/activity_schedule.xml
  PlanJ/app/src/main/res/menu/top_complete_menu.xml
  PlanJ/app/src/main/res/values/colors.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat

#66 [K041] 주간 달럭 뷰홀더 제작
  PlanJ/app/src/main/java/com/boostcamp/planj/data/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CalendarAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/WeekScheduleAdapter.kt
  PlanJ/app/src/main/res/layout/item_day.xml
  PlanJ/app/src/main/res/layout/item_week_end.xml
  PlanJ/app/src/main/res/layout/item_week_schedule.xml
  PlanJ/app/src/main/res/layout/item_week_start.xml
  PlanJ/app/src/main/res/values/colors.xml
Labels: :art: Design

#67 [J033] Schedule 부분 skeleton
  be/src/auth/auth.module.ts
  be/src/auth/entity/user.entity.ts
  be/src/auth/user.repository.ts
  be/src/schedule/schedule.controller.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat, :stethoscope: Refactor

#69 [K020] 일정 추가 화면 데이터 바인딩 및 클릭 이벤트
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/activity_schedule.xml
Labels: And, :field_hockey: Feat

#71 [J033] schedule entity 작성
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/entity/schedule.meta.entity.ts
Labels: Be, Must, :field_hockey: Feat

#72 [J161] 일정 추가 로직 초안 작성
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/schedule.controller.ts
  be/src/schedule/schedule.module.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat

#73 [J033] participant.entity.ts 작성
  be/src/auth/entity/user.entity.ts
  be/src/schedule/entity/participant.entity.ts
  be/src/schedule/entity/schedule.meta.entity.ts
Labels: Be, Must, :field_hockey: Feat

#74 [K020] 일정추가 UI에서 카테고리 선택 메뉴로 변경
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/activity_schedule.xml
  PlanJ/app/src/main/res/values/styles.xml
Labels: And, :field_hockey: Feat

#76 [J161] addSchedule() 실행 시 ScheduleMeta 테이블과 Schedule 테이블 모두에 데이터가 저장되도록 구현
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/schedule.meta.repository.ts
  be/src/schedule/schedule.module.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat

#77 [J033] 서버용 스크립트 수정
  be/package.json
Labels: Be, Must, :lady_beetle: Fix

#80 [J161] 아키텍처 계획 변경에 따른 모듈 생성 및 의존 관계 설정
  be/src/app.module.ts
  be/src/auth-api/auth-api.controller.spec.ts
  be/src/auth-api/auth-api.controller.ts
  be/src/auth-api/auth-api.module.ts
  be/src/auth/auth.controller.spec.ts
  be/src/category-api/category-api.controller.spec.ts
  be/src/category-api/category-api.controller.ts
  be/src/category-api/category-api.module.ts
  be/src/category/category.module.ts
  be/src/category/category.service.spec.ts
  be/src/category/category.service.ts
  be/src/schedule-api/schedule-api.controller.spec.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.module.ts
  be/src/schedule-meta-data/schedule-meta-data.module.ts
  be/src/schedule-meta-data/schedule-meta-data.service.spec.ts
  be/src/schedule-meta-data/schedule-meta-data.service.ts
  be/src/schedule/entity/participant.entity.ts
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/entity/schedule.meta.entity.ts
  be/src/schedule/schedule.entity.ts
  be/src/schedule/schedule.module.ts
  be/src/user/auth.service.spec.ts
  be/src/user/dto/create-user.dto.ts
  be/src/user/dto/user-login.dto.ts
  be/src/user/dto/user-modify.dto.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: Be, Must, :stethoscope: Refactor

#88 [K020] 일정 추가 화면 -> 상세/편집으로 변경, 카테고리 데이터 클래스 추가
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AppDatabase.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/CategoryDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Category.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/drawable/ic_delete_schedule.xml
  PlanJ/app/src/main/res/drawable/ic_edit_schedule.xml
  PlanJ/app/src/main/res/layout/activity_schedule.xml
  PlanJ/app/src/main/res/menu/top_complete_menu.xml
  PlanJ/app/src/main/res/menu/top_schedule_menu.xml
  PlanJ/app/src/main/res/values/strings.xml
  PlanJ/app/src/main/res/values/styles.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix

#89 [J161] 카테고리 생성 로직, 스케줄 생성 로직 구현
  be/src/category-api/category-api.controller.ts
  be/src/category-api/category-api.module.ts
  be/src/category-api/category-api.service.spec.ts
  be/src/category-api/category-api.service.ts
  be/src/category/add-category.service.ts
  be/src/category/category.module.ts
  be/src/category/category.repository.ts
  be/src/category/category.service.spec.ts
  be/src/category/category.service.ts
  be/src/category/dto/add-category.dto.ts
  be/src/category/entity/category.entity.ts
  be/src/category/get-user-entity.service.ts
  be/src/category/user.check.repository.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.module.ts
  be/src/schedule-api/schedule-api.service.spec.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/add-schedule-metadata.service.ts
  be/src/schedule/add-schedule.service.ts
  be/src/schedule/category.check.repository.ts
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/entity/participant.entity.ts
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/entity/schedule.meta.entity.ts
  be/src/schedule/get-category-entity.service.ts
  be/src/schedule/get-user-entity.service.ts
  be/src/schedule/schedule.meta.repository.ts
  be/src/schedule/schedule.module.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
  be/src/schedule/user.check.repository.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.repository.ts
Labels: Be, Must, :field_hockey: Feat, :stethoscope: Refactor

#90 [J161] 일간 일정 조회 로직 구현
  be/src/category-api/category-api.controller.ts
  be/src/category-api/category-api.service.ts
  be/src/category/category.module.ts
  be/src/category/category.repository.ts
  be/src/category/category.service.ts
  be/src/category/entity/category.entity.ts
  be/src/category/get-user-entity.service.ts
  be/src/category/user.check.repository.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/add-schedule-metadata.service.ts
  be/src/schedule/category.check.repository.ts
  be/src/schedule/entity/schedule-meta.entity.ts
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/get-category-entity.service.ts
  be/src/schedule/get-user-entity.service.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.module.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
  be/src/schedule/user.check.repository.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: Be, Must, :field_hockey: Feat, :stethoscope: Refactor

#91 [K026] 카테고리 전체적인 부분 구현
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AppDatabase.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/CategoryDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/User.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/category/CategoryDetailActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/category/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/category/CategoryDetailViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CategoryClickListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CategoryDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CategoryFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CategoryPopUpMenuListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CategoryViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/HomeFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/ScheduleClickListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/CategoryListAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/CategoryListAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/ScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/ScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/activity_category.xml
  PlanJ/app/src/main/res/layout/add_dialog.xml
  PlanJ/app/src/main/res/layout/dialog_add_category.xml
  PlanJ/app/src/main/res/layout/dialog_add_schedule.xml
  PlanJ/app/src/main/res/layout/fragment_category.xml
  PlanJ/app/src/main/res/layout/fragment_category_detail.xml
  PlanJ/app/src/main/res/layout/fragment_home.xml
  PlanJ/app/src/main/res/layout/fragment_list.xml
  PlanJ/app/src/main/res/layout/fragment_today.xml
  PlanJ/app/src/main/res/layout/item_dropdown.xml
  PlanJ/app/src/main/res/layout/item_list_category.xml
  PlanJ/app/src/main/res/layout/item_schedule.xml
  PlanJ/app/src/main/res/menu/bottom_menu.xml
  PlanJ/app/src/main/res/menu/category_popup_menu.xml
  PlanJ/app/src/main/res/menu/top_complete_menu.xml
  PlanJ/app/src/main/res/navigation/category_nav.xml
  PlanJ/app/src/main/res/navigation/main_nav.xml
  PlanJ/app/src/main/res/values/themes.xml
  PlanJ/build.gradle.kts
  PlanJ/gradle/libs.versions.toml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor

#92 [K020] DatePicker/TimePicker, 반복/알림 다이얼로그 추가
  PlanJ/.idea/misc.xml
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/LoginResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Repetition.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SignInRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SignUpResult.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/LoginActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/WeekFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialogListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialogListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/SetDialogSize.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
  PlanJ/app/src/main/res/color/selector_text_color.xml
  PlanJ/app/src/main/res/layout/activity_schedule.xml
  PlanJ/app/src/main/res/layout/dialog_alarm_setting.xml
  PlanJ/app/src/main/res/layout/dialog_repetition_setting.xml
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/layout/fragment_sign_in.xml
  PlanJ/app/src/main/res/layout/fragment_sign_up.xml
  PlanJ/app/src/main/res/layout/item_participant.xml
  PlanJ/app/src/main/res/navigation/schedule_nav.xml
  PlanJ/app/src/main/res/values/colors.xml
  PlanJ/app/src/main/res/values/strings.xml
  PlanJ/gradle/libs.versions.toml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor

#93 [K041] 주간 화면 달력, 주간 통계 확인하기
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CalendarAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MyFragmentPagerAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/WeekFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/WeekScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/ScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/ScheduleSimpleViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/WeekFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/adapter/CalendarAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/adapter/CalendarViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/adapter/ScheduleSimpleViewAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/adapter/ScheduleSimpleViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/adapter/StartAndEndScheduleViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/adapter/TodayScheduleViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/week/adapter/WeekScheduleAdapter.kt
  PlanJ/app/src/main/res/drawable/ic_close.xml
  PlanJ/app/src/main/res/layout/dailog_schedule_result.xml
  PlanJ/app/src/main/res/layout/fragment_week.xml
  PlanJ/app/src/main/res/layout/item_week_day.xml
  PlanJ/app/src/main/res/layout/item_week_schedule.xml
  PlanJ/app/src/main/res/layout/item_week_start.xml
  PlanJ/app/src/main/res/layout/item_week_start_and_end.xml
  PlanJ/app/src/main/res/values/strings.xml
  PlanJ/app/src/main/res/values/week_array.xml
Labels: And, :field_hockey: Feat, :stethoscope: Refactor

#94 [J161] 주간 일정 조회 기능 구현, 일정 수정 기능 구현
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/dto/update-schedule.dto.ts
  be/src/schedule/entity/schedule-meta.entity.ts
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix

#106 [J033] Dockerfile, docker-compose.yml 작성
  be/Dockerfile
  be/docker-compose.yml
  be/nginx/Dockerfile
  be/nginx/default.conf
Labels: Be, Must, :field_hockey: Feat

#107 [J161] 카테고리 삭제, 스케줄 삭제 기능 구현
  be/src/category-api/category-api.controller.ts
  be/src/category-api/category-api.service.ts
  be/src/category/category.repository.ts
  be/src/category/category.service.ts
  be/src/category/dto/delete-category.dto.ts
  be/src/category/entity/category.entity.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule-meta-data/schedule-meta-data.module.ts
  be/src/schedule-meta-data/schedule-meta-data.service.spec.ts
  be/src/schedule-meta-data/schedule-meta-data.service.ts
  be/src/schedule/dto/delete-schedule.dto.ts
  be/src/schedule/entity/schedule-meta.entity.ts
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
  be/src/user/entity/user.entity.ts
Labels: Be, Must, :field_hockey: Feat, :stethoscope: Refactor

#117 [J161] 일정 수정 시 위치 정보 추가 기능 구현, 친구 추가 모듈 생성
  be/src/app.module.ts
  be/src/friend/dto/add-friend.dto.ts
  be/src/friend/entity/friends.entity.ts
  be/src/friend/friend.controller.spec.ts
  be/src/friend/friend.controller.ts
  be/src/friend/friend.module.ts
  be/src/friend/friend.repository.ts
  be/src/friend/friend.service.spec.ts
  be/src/friend/friend.service.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/update-schedule.dto.ts
  be/src/schedule/entity/schedule-location.entity.ts
  be/src/schedule/schedule-location.respository.ts
  be/src/schedule/schedule-location.service.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.module.ts
Labels: Be, Must, :field_hockey: Feat

#108 [K020] 친구 목록 화면 및 관련 다이얼로그
  PlanJ/.idea/misc.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AppDatabase.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/TypeConverter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/UserDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Alarm.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/User.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/AddFriendDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/AddFriendDialogListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendClickListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendInfoDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialogListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/dialog_add_friend.xml
  PlanJ/app/src/main/res/layout/dialog_friend_info.xml
  PlanJ/app/src/main/res/layout/fragment_friend_list.xml
  PlanJ/app/src/main/res/layout/item_friend.xml
  PlanJ/app/src/main/res/layout/item_participant.xml
  PlanJ/app/src/main/res/menu/friend_menu.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat

#110 [K026] 네이버 지도를 이용해 주소를 선택하기
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/PlanjApplication.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/SearchMapModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Address.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Location.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Meta.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SameName.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SearchMap.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/KaKaoSearchApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/SearchRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/SearchRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleSearchAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleSearchAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/SearchMapClickListener.kt
  PlanJ/app/src/main/res/drawable/round_search_background.xml
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/layout/fragment_schedule_map.xml
  PlanJ/app/src/main/res/layout/item_search_map.xml
  PlanJ/app/src/main/res/navigation/schedule_nav.xml
  PlanJ/gradle.properties
  PlanJ/gradle/libs.versions.toml
  PlanJ/settings.gradle.kts
Labels: And, :field_hockey: Feat, :lady_beetle: Fix

#119 [J033] 충돌해결, JWT 토큰 부분 구현
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/auth-api/auth-api.controller.ts
  be/src/auth-api/auth-api.module.ts
  be/src/auth-api/auth-api.service.ts
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.spec.ts
  be/src/auth/auth.service.ts
  be/src/config/auth.config.ts
  be/src/config/db.config.ts
  be/src/config/typeorm.config.ts
  be/src/guard/auth.guard.ts
  be/src/user/dto/user-modify.dto.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix, :abacus: Chore, :stethoscope: Refactor

#118 [K020] 일정 상세 화면 이동
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/CategoryDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/today/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/navigation/schedule_nav.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :lady_beetle: Fix, :stethoscope: Refactor

#127 [K026] 서버 연결하기, 이벤트 동작 하기
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/CategoryDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/DeleteCategoryBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/DeleteScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/LoginResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PatchScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PatchScheduleResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PostCategoryBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PostCategoryResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PostScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PostScheduleResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/PlanJAPI.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleDoneListener.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/SegmentScheduleAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/SegmentScheduleAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/today/TodayFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/today/TodayViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
Labels: And, :field_hockey: Feat, :lady_beetle: Fix

#126 [K020] 검색, 설정 화면
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchViewModel.kt
  PlanJ/app/src/main/res/drawable/ic_edit.xml
  PlanJ/app/src/main/res/layout/activity_search.xml
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/layout/fragment_setting.xml
  PlanJ/app/src/main/res/menu/search_menu.xml
  PlanJ/app/src/main/res/menu/top_schedule_menu.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat, :art: Design

#121 [K041] 주간 화면 기능 개선
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/WeekSchedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragmentViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/CalendarAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/CalendarViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/ScheduleSimpleViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/StartAndEndScheduleViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/TodayScheduleViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/WeekScheduleAdapter.kt
  PlanJ/app/src/main/res/layout/dialog_schedule_result.xml
  PlanJ/app/src/main/res/layout/fragment_week.xml
  PlanJ/app/src/main/res/layout/item_week_day.xml
  PlanJ/app/src/main/res/layout/item_week_schedule.xml
  PlanJ/app/src/main/res/layout/item_week_start_and_end.xml
Labels: And, :lady_beetle: Fix, :stethoscope: Refactor

#128 [J033] 토큰 기반 사용자 삭제
  be/src/app.module.ts
  be/src/auth-api/auth-api.controller.ts
  be/src/auth-api/auth-api.module.ts
  be/src/auth-api/auth-api.service.ts
  be/src/auth/auth.module.ts
  be/src/auth/auth.service.spec.ts
  be/src/auth/auth.service.ts
  be/src/category-api/category-api.controller.ts
  be/src/category/entity/category.entity.ts
  be/src/config/auth.config.ts
  be/src/friend/entity/friends.entity.ts
  be/src/friend/friend.controller.spec.ts
  be/src/friend/friend.service.spec.ts
  be/src/guard/auth.guard.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/delete-schedule.dto.ts
  be/src/schedule/dto/update-schedule.dto.ts
  be/src/schedule/entity/schedule-location.entity.ts
  be/src/schedule/entity/schedule-metadata.entity.ts
  be/src/schedule/entity/schedule.entity.ts
  be/src/schedule/schedule-location.repository.ts
  be/src/schedule/schedule-location.service.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.module.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
  be/src/user-api/user-api.controller.spec.ts
  be/src/user-api/user-api.controller.ts
  be/src/user-api/user-api.module.ts
  be/src/user-api/user-api.service.ts
  be/src/user/dto/user-modify.dto.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.module.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: Be, Must, :field_hockey: Feat, :abacus: Chore

#133 [J033] 오타 수정
  be/src/schedule/schedule-location.repository.ts
Labels: Be, Must, :lady_beetle: Fix

#134 [J033] jwt를 이용한 회원 기능 추가
  be/src/user-api/user-api.controller.ts
  be/src/user-api/user-api.service.ts
  be/src/user/user.service.ts
Labels: Be, Must, :field_hockey: Feat

#135 [J033] method 이름 변경
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: Be, Could, :stethoscope: Refactor

#136 [J033] 헤더에서 jwt를 추출하는 데코레이터 구현
  be/src/auth/auth.service.ts
  be/src/user-api/user-api.controller.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
  be/src/utils/token.decorator.ts
Labels: Be, Could, :field_hockey: Feat, :abacus: Chore

#137 [J033] guard 적용
  be/src/category-api/category-api.controller.ts
  be/src/category-api/category-api.module.ts
  be/src/category-api/category-api.service.ts
  be/src/category/category.repository.ts
  be/src/category/dto/add-category.dto.ts
  be/src/category/dto/delete-category.dto.ts
  be/src/category/entity/category.entity.ts
  be/src/config/typeorm.config.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.module.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/dto/delete-schedule.dto.ts
  be/src/schedule/dto/update-schedule.dto.ts
  be/src/schedule/schedule.module.ts
Labels: Be, Must, :stethoscope: Refactor

#143 [J033] 기본 카테고리 조회 추가
  be/src/category-api/category-api.controller.ts
  be/src/category-api/category-api.service.ts
  be/src/category/category.repository.ts
  be/src/category/category.service.ts
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/dto/schedule.response.ts
  be/src/schedule/schedule-location.repository.ts
  be/src/schedule/schedule-location.service.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor

#144 [J161] 친구 목록 추가 및 조회 기능 구현, participant 테이블 추가
  be/src/friend/entity/friend.entity.ts
  be/src/friend/entity/friends.entity.ts
  be/src/friend/friend.controller.ts
  be/src/friend/friend.module.ts
  be/src/friend/friend.repository.ts
  be/src/friend/friend.service.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/invite-schedule.dto.ts
  be/src/schedule/entity/participant.entity.ts
  be/src/schedule/entity/schedule-metadata.entity.ts
  be/src/schedule/participate.repository.ts
  be/src/schedule/participate.service.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule.module.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix

#146 [K020] 참가자 목록 전체보기 및 완료 여부 시각적으로 보이도록 구현
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Participant.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapterViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/SetDialogSize.kt
  PlanJ/app/src/main/res/drawable/ic_done.xml
  PlanJ/app/src/main/res/drawable/ic_not_done.xml
  PlanJ/app/src/main/res/layout/dialog_participants.xml
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/layout/item_participant.xml
  PlanJ/app/src/main/res/values/colors.xml
  PlanJ/app/src/main/res/values/strings.xml
Labels: And, :field_hockey: Feat

#156 [J161] 친구 추가 api 입력 형식 변경, 일정 초대 기능 구현
  be/src/friend/dto/add-friend.dto.ts
  be/src/friend/friend.service.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/add-schedule.dto.ts
  be/src/schedule/dto/invite-schedule.dto.ts
  be/src/schedule/dto/update-schedule.dto.ts
  be/src/schedule/entity/participant.entity.ts
  be/src/schedule/entity/schedule-metadata.entity.ts
  be/src/schedule/participate.repository.ts
  be/src/schedule/participate.service.ts
  be/src/schedule/schedule-location.service.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.repository.ts
  be/src/schedule/schedule.service.ts
  be/src/user/user.repository.ts
  be/src/user/user.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix

#153 [K020] 알람 설정
  PlanJ/app/build.gradle.kts
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/PlanJReceiver.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/AlarmRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/AlarmRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialog.kt
Labels: And, Must, :field_hockey: Feat

#154 [K026] 네이버 지도 연동, 일정화면에서 지도 보이게 설정, 알림 설정 및 다른 대중교통(url scheme 적용)
  PlanJ/app/src/main/AndroidManifest.xml
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PostScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/CalendarViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleBottomSheetDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleMapViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleShowMapFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleStartMapViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/drawable/round_r8_red.xml
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/layout/fragment_show_map.xml
  PlanJ/app/src/main/res/layout/item_week_day.xml
  PlanJ/app/src/main/res/layout/schedule_bottom_sheet.xml
  PlanJ/app/src/main/res/navigation/map_show_nav.xml
  PlanJ/app/src/main/res/values/themes.xml
Labels: And, :field_hockey: Feat, :lady_beetle: Fix

#155 [K020] api 요청 추가 및 수정
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AppDatabase.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/DeleteCategoryBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/DeleteScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/PatchScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Repetition.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/DeleteScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetCategoryResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetFriendResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetSchedulesResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PatchCategoryRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PatchCategoryResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PatchScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PatchScheduleResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PostCategoryBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PostCategoryResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PostFriendRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PostScheduleBody.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PostScheduleResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/SignInRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/SignUpRequest.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/SignUpResult.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/LoginApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/MainApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/today/TodayViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
Labels: And, Must, :field_hockey: Feat

#158 [J033] 회원 정보 조회 추가
  be/src/user-api/user-api.controller.ts
  be/src/user-api/user-api.service.ts
Labels: Be, Must, :field_hockey: Feat

#159 [J033] 미분류 카테고리에 일정 추가 안되는 문제 해결
  be/src/category/category.service.ts
Labels: Be, Must, :lady_beetle: Fix

#160 [K041] 주간 화면 수정, 다이얼로그 구현부분 수정
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragmentViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/CalendarAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/CalendarViewHolder.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/WeekScheduleAdapter.kt
  PlanJ/app/src/main/res/layout/item_week_day.xml
Labels: And, :field_hockey: Feat, :stethoscope: Refactor

#161 [J033] 사용자 이미지 업로드 추가
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/config/aws.config.ts
  be/src/image/image.module.ts
  be/src/image/image.service.spec.ts
  be/src/image/image.service.ts
  be/src/user-api/user-api.controller.ts
  be/src/user-api/user-api.module.ts
  be/src/user-api/user-api.service.ts
  be/src/user/entity/user.entity.ts
  be/src/user/user.service.ts
Labels: Be, Should, :field_hockey: Feat

#162 [J161] 사용자 초대 기능 오류 수정
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/entity/participant.entity.ts
  be/src/schedule/entity/schedule-metadata.entity.ts
  be/src/schedule/participate.repository.ts
  be/src/schedule/participate.service.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat

#163 [K020] api 요청 추가, 알람 정보 로컬에 저장
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AlarmInfoDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/TypeConverter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/AlarmInfo.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/DateTime.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/AlarmRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/AlarmRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/today/TodayViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragmentViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleDialog.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
  PlanJ/app/src/main/res/drawable/ic_naver.png
  PlanJ/app/src/main/res/layout/fragment_schedule.xml
  PlanJ/app/src/main/res/layout/fragment_sign_in.xml
Labels: And, :field_hockey: Feat

#165 [K026] 설정화면 프로필 수정, 로그아웃, 회원탈퇴, 알람설정
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AlarmInfoDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/CategoryDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/db/UserDao.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/User.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/GetUserInfoResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/model/dto/PostUserResponse.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/LoginApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/network/MainApi.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/category/CategoryViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleStartMapViewModel.kt
  PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchViewModel.kt
  PlanJ/app/src/main/res/drawable/ic_camera.xml
  PlanJ/app/src/main/res/drawable/ic_circle_person.xml
  PlanJ/app/src/main/res/layout/fragment_setting.xml
  PlanJ/app/src/main/res/navigation/main_nav.xml
Labels: And, Must, :field_hockey: Feat

#166 [J033] 의존성으로 인한 오류 해결
  be/src/schedule/dto/schedule-alarm.dto.ts
  be/src/schedule/dto/update-schedule.dto.ts
  be/src/schedule/entity/schedule-alarm.entity.ts
  be/src/schedule/schedule.module.ts
  be/src/user-api/user-api.controller.ts
Labels: Be, Must, :lady_beetle: Fix

#168 [J161] 일간, 주간 일정 조회 시 반복 여부, 알람 설정 여부, 참가자 수 및 성공한 참가자 수 응답
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/dto/schedule.response.ts
  be/src/schedule/participate.service.ts
  be/src/schedule/schedule-meta.repository.ts
  be/src/schedule/schedule-meta.service.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix

#169 [J033] 사용자가 일정을 체크할 때 처리 구현
  be/src/friend/friend.service.ts
  be/src/schedule-api/schedule-api.controller.ts
  be/src/schedule-api/schedule-api.service.ts
  be/src/schedule/schedule.service.ts
Labels: Be, Must, :field_hockey: Feat, :lady_beetle: Fix, :stethoscope: Refactor
